package com.survivemum.app.security.models

import java.util.UUID

/**
 * Alert priority levels — determines routing and send urgency.
 * CRITICAL and HIGH override battery-saving to ensure delivery.
 */
enum class AlertPriority {
    CRITICAL,  // Preeclampsia, respiratory distress — send immediately
    HIGH,      // Abnormal vitals trend — send within minutes
    MEDIUM,    // Missed ANC visit — send when convenient
    LOW        // Routine follow-up — batch and send
}

/**
 * Clinical alert types — what danger was detected.
 */
enum class AlertType {
    PREECLAMPSIA,
    RESPIRATORY_DISTRESS,
    JAUNDICE,
    CRY_ABNORMAL,
    VITAL_TREND,
    MISSED_VISIT,
    DEVELOPMENTAL_DELAY,
    MOVEMENT_ASYMMETRY
}

/**
 * What action the TBA should take.
 */
enum class RecommendedAction {
    REFER_HOSPITAL,
    MONITOR_CLOSELY,
    SCHEDULE_VISIT,
    IMMEDIATE_TRANSPORT
}

/**
 * Result from ShieldGemma safety screening.
 */
enum class SafetyVerdict {
    SAFE,
    UNSAFE,
    FLAGGED  // Not blocked, but logged for review
}

/**
 * Result from ShieldGemma safety screening.
 *
 * verdict             — overall decision (SAFE / FLAGGED / UNSAFE)
 * reason              — human-readable summary, used in audit log and TBA fallback messages
 * policiesViolated    — list of every policy violated (was a single String, now a list
 *                       so we don't lose information when multiple violations occur)
 * confidence          — 0.0–1.0; how certain the screener is about this verdict.
 *                       Computed from violation count and severity (see SafetyScreener).
 * categoryScores      — per-category scores from ShieldGemma (e.g. "dangerous_content" → 0.78)
 *                       Empty when running rule-based fallback.
 * screeningMs         — wall time taken to produce this result, used for latency metrics.
 *                       0 when not measured.
 */
data class SafetyResult(
    val verdict: SafetyVerdict,
    val reason: String? = null,
    val policiesViolated: List<String> = emptyList(),
    val confidence: Double = 0.0,
    val categoryScores: Map<String, Double> = emptyMap(),
    val screeningMs: Long = 0
)

/**
 * Battery states — drives model routing and frame rate decisions.
 */
enum class BatteryState {
    CRITICAL,   // 0-10%
    LOW,        // 10-25%
    MEDIUM,     // 25-50%
    GOOD,       // 50-100%
    CHARGING    // Any level, plugged in
}

/**
 * Which Gemma model to use.
 */
enum class ModelSize {
    E2B,   // Small, fast, low battery cost
    E4B    // Big, smart, high battery cost
}

/**
 * Types of requests the AI can receive — determines model routing.
 */
enum class RequestType {
    SIMPLE_QUERY,
    VITAL_DISPLAY,
    CRY_CLASSIFICATION,
    CLINICAL_ASSESSMENT,
    PREECLAMPSIA_CHECK,
    EMERGENCY_TRIAGE
}

/**
 * Device capability level — combines battery, temperature,
 * and drain rate into one decision for ModelRouter.
 */
enum class DeviceCapability {
    FULL,       // Everything available — use E4B freely
    REDUCED,    // Conserve — prefer E2B, E4B for clinical only
    MINIMAL,    // Emergency only — E2B default, E4B for life-threatening
    THROTTLED   // Overheating — E2B only, reduce frame rate, alert TBA
}

/**
 * Vital signs measured by the rPPG pipeline (BE-1's territory) plus
 * any other vital data extracted from camera, audio, or manual entry.
 *
 * All fields nullable because not every assessment captures every vital.
 * A cry classification produces no BP. A BP check produces no SpO2.
 */
data class VitalSigns(
    val heartRate: Int? = null,            // beats per minute
    val spO2: Int? = null,                 // blood oxygen %, 0-100
    val bloodPressureSystolic: Int? = null,   // mmHg
    val bloodPressureDiastolic: Int? = null,  // mmHg
    val temperature: Float? = null,        // Celsius
    val respiratoryRate: Int? = null       // breaths per minute
)

/**
 * Clinical alert generated by Gemma E4B, screened by ShieldGemma,
 * and dispatched by AlertDispatcher.
 *
 * The full lifecycle:
 *   1. Gemma generates the alert (summary, reasoning, recommended action)
 *   2. SafetyScreener.screenOutput evaluates it → populates safetyResult
 *   3. If safe, AlertDispatcher queues and delivers it
 *   4. Delivery success populates sent + sentAt
 *
 * alertId uses UUID so it survives database persistence and SMS retries.
 */
data class Alert(
    val alertId: String = UUID.randomUUID().toString(),
    val type: AlertType,
    val priority: AlertPriority,
    val patientId: String,

    // The clinical content — what Gemma generated
    val summary: String,                   // short headline shown in SMS
    val reasoning: String,                 // full reasoning trace
    val recommendedAction: RecommendedAction,
    val confidence: Double = 0.0,          // Gemma's confidence in the alert

    // Optional clinical context
    val vitalSigns: VitalSigns? = null,

    // Delivery metadata
    val recipientPhone: String? = null,    // health worker's WhatsApp/SMS number
    val timestamp: Long = System.currentTimeMillis(),
    val sent: Boolean = false,
    val sentAt: Long? = null,

    // Populated by SafetyScreener.screenOutput before dispatch.
    // Null = not yet screened. UNSAFE = should not have been queued.
    val safetyResult: SafetyResult? = null
)