package com.survivemum.data

import androidx.room.*
import kotlinx.coroutines.flow.Flow

/**
 * Data Access Object for managing health alerts.
 * Acts as the bridge between Gemma's AI reasoning and the user interface.
 */
@Dao
interface AlertDao {

    /**
     * Retrieves the complete history of AI detections for a specific patient.
     * Used for the "Patient History Timeline" screen.
     */
    @Query("SELECT * FROM alerts WHERE patientId = :patientId ORDER BY timestamp DESC")
    fun getAlertsForPatient(patientId: String): Flow<List<AlertEntity>>

    /**
     * Fetches the 5 most recent alerts across all mothers under a specific TBA's care.
     * Powers the "Home Dashboard" for quick situational awareness.
     */
    @Query("SELECT * FROM alerts WHERE patientId IN (SELECT patientId FROM patients WHERE tbaId = :tbaId) ORDER BY timestamp DESC LIMIT 5")
    fun getRecentAlerts(tbaId: String): Flow<List<AlertEntity>>

    /**
     * Filters for alerts that haven't been acknowledged by the user yet.
     * Essential for the "Emergency Alert" screen to ensure no life-threatening flag is missed.
     */
    @Query("SELECT * FROM alerts WHERE patientId = :patientId AND actionConfirmedAt IS NULL ORDER BY timestamp DESC")
    fun getUnconfirmedAlerts(patientId: String): Flow<List<AlertEntity>>

    /**
     * Persists a new detection generated by the on-device AI.
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAlert(alert: AlertEntity)

    /**
     * Logs the human response to an AI flag.
     * Stores what action was taken (e.g., "Referred to Clinic") to close the safety loop.
     */
    @Query("UPDATE alerts SET actionConfirmedAt = :timestamp, actionTaken = :action WHERE alertId = :alertId")
    suspend fun confirmAction(alertId: String, timestamp: String, action: String)

    /**
     * Counts active CRITICAL or HIGH severity flags.
     * Powers the red notification badge on the "Home Dashboard".
     */
    @Query("SELECT COUNT(*) FROM alerts WHERE patientId IN (SELECT patientId FROM patients WHERE tbaId = :tbaId) AND actionConfirmedAt IS NULL AND severity IN ('CRITICAL','HIGH')")
    suspend fun getUnconfirmedCriticalCount(tbaId: String): Int
}
