package com.survivemum.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a medical alert generated by the on-device AI.
 * This entity captures the reasoning, confidence, and action steps
 * for critical maternal and infant health events.
 */
@Entity(tableName = "alerts")
data class AlertEntity(
    @PrimaryKey 
    val alertId: String,          // Unique identifier for the alert

    val patientId: String,        // Links the alert to a specific Mother or Child

    val timestamp: String,        // When the alert was generated

    val severity: String,         // Severity level (e.g., CRITICAL, HIGH, MEDIUM, LOW)

    val alertType: String,        // The category (e.g., Respiratory, Jaundice, BP Trend)

    val layer: String,            // Source of alert: MOTHER, NEWBORN, or TODDLER

    val title: String,            // A short, clear headline for the user (e.g., "Meningitis Flag")

    val message: String,          // Detailed explanation of the current finding

    val actionRequired: String,   // Immediate clinical steps the user should take

    /**
     * The internal "logic" or chain-of-thought from Gemma.
     * Essential for clinical audit and understanding the AI's "Silent Guardian" process.
     */
    val thinkingTrace: String,    

    val gemmaConfidence: Float,   // The probability score assigned by the AI

    /**
     * Citation of a verified medical guideline (e.g., WHO or Ministry of Health).
     * Prevents misinformation by anchoring AI output to facts.
     */
    val ragGuidelineCited: String? = null,

    val language: String = "en",  // Localization for the guardian

    val referralLetterGenerated: Int = 0, // 1 if a PDF/Text referral was created, else 0

    val actionConfirmedAt: String? = null, // Timestamp when the user acknowledged the alert

    val actionTaken: String? = null,       // Log of what the user did (e.g., "Referred to Hospital")

    val fullJson: String          // Raw JSON for debugging or future feature extraction
)
