package com.survivemum.data

import androidx.room.*
import kotlinx.coroutines.flow.Flow

/**
 * Data Access Object for infant cry analysis.
 * Manages the acoustic classifications generated by the on-device AI to protect 
 * those who cannot speak for themselves.
 */
@Dao
interface CryEventDao {

    /**
     * Retrieves the chronological history of cry classifications for a specific infant.
     * Used to populate the 'Acoustic Timeline' to track behavioral or health changes over time.
     * Returns a Flow to ensure the UI updates automatically when new data is inserted.
     */
    @Query("SELECT * FROM cry_events WHERE patientId = :patientId ORDER BY timestamp DESC")
    fun getCryEventsForPatient(patientId: String): Flow<List<CryEventEntity>>

    /**
     * Filters for cry events that indicate clinical danger (e.g., potential Meningitis or respiratory distress).
     * Powers the 'Emergency Alert' screen by isolating high-risk patterns from routine cries.
     * This is critical for 100% offline triage in rural settings.
     */
    @Query("SELECT * FROM cry_events WHERE patientId = :patientId AND clinicalFlag = 1 ORDER BY timestamp DESC")
    fun getFlaggedCryEvents(patientId: String): Flow<List<CryEventEntity>>

    /**
     * Persists a new cry classification into the local database after AI processing.
     * Uses [OnConflictStrategy.REPLACE] to ensure clinical records are updated rather than duplicated.
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertCryEvent(cryEvent: CryEventEntity)
}
