import { useState, useMemo, useCallback } from 'react';
import { generateReferral } from '../ai/generateReferral';
import ActionButton from '../components/ActionButton';

const LANGS = ['EN', 'HA', 'YO', 'IG'];

const LANG_LABELS = { EN: '🇬🇧 English', HA: 'Hausa', YO: 'Yoruba', IG: 'Igbo' };

function getPatient() {
  try {
    const stored = localStorage.getItem('anc_patient');
    return stored ? JSON.parse(stored) : {};
  } catch { return {}; }
}

export default function ReferralLetter() {
  const [lang, setLang] = useState('EN');
  const [toast, setToast] = useState(null);

  const patient = useMemo(() => getPatient(), []);
  const referral = useMemo(() => generateReferral(patient, lang), [patient, lang]);

  const showToast = useCallback((msg) => {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  }, []);

  const handleShare = useCallback(() => {
    if (navigator.share) {
      navigator.share({ title: 'SurviveMum Referral', text: referral.text });
    } else {
      navigator.clipboard?.writeText(referral.text);
      showToast('Letter copied to clipboard ✓');
    }
  }, [referral.text, showToast]);

  const handleWhatsApp = useCallback(() => {
    const encoded = encodeURIComponent(referral.text);
    window.open(`https://wa.me/?text=${encoded}`, '_blank');
  }, [referral.text]);

  const handleSMS = useCallback(() => {
    const encoded = encodeURIComponent(referral.text.slice(0, 500));
    window.open(`sms:?body=${encoded}`, '_blank');
  }, [referral.text]);

  const handlePrint = useCallback(() => {
    const w = window.open('', '_blank');
    w.document.write(`<pre style="font-family:monospace;white-space:pre-wrap;padding:24px">${referral.text}</pre>`);
    w.print();
    showToast('Print dialog opened');
  }, [referral.text, showToast]);

  return (
    <div className="animate-slide-up" style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <div>
          <h1 style={{ fontSize: '1.2rem' }}>Referral Letter</h1>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-3)', marginTop: 2 }}>Auto-generated by AI</p>
        </div>
        <span style={{ fontSize: '0.75rem', background: 'rgba(239,68,68,0.15)', color: 'var(--red)', padding: '4px 10px', borderRadius: '999px', fontWeight: 700 }}>
          {referral.urgency}
        </span>
      </div>

      {/* Language Selector */}
      <div>
        <div className="label" style={{ marginBottom: 8 }}>Language</div>
        <div className="lang-tabs">
          {LANGS.map(l => (
            <button
              key={l}
              id={`lang-tab-${l}`}
              className={`lang-tab${lang === l ? ' active' : ''}`}
              onClick={() => setLang(l)}
            >
              {LANG_LABELS[l]}
            </button>
          ))}
        </div>
      </div>

      {/* Letter Body */}
      <div className="card">
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 12 }}>
          <span style={{ fontSize: '1.2rem' }}>📄</span>
          <div>
            <div style={{ fontSize: '0.875rem', fontWeight: 600 }}>Medical Referral</div>
            <div style={{ fontSize: '0.75rem', color: 'var(--text-4)' }}>{referral.facility}</div>
          </div>
        </div>
        <div className="divider" />
        <pre className="letter-body">{referral.text}</pre>
      </div>

      {/* Action Buttons */}
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
        <button id="btn-whatsapp" onClick={handleWhatsApp} style={{
          flex: '1', minWidth: 120,
          background: '#25D366', color: '#fff', border: 'none',
          borderRadius: 'var(--radius-md)', padding: '12px 8px',
          fontFamily: 'inherit', fontSize: '0.875rem', fontWeight: 600, cursor: 'pointer',
        }}>
          📲 WhatsApp
        </button>
        <button id="btn-sms" onClick={handleSMS} style={{
          flex: '1', minWidth: 100,
          background: 'var(--surface-2)', color: 'var(--text)', border: '1px solid var(--border)',
          borderRadius: 'var(--radius-md)', padding: '12px 8px',
          fontFamily: 'inherit', fontSize: '0.875rem', fontWeight: 600, cursor: 'pointer',
        }}>
          💬 SMS
        </button>
        <button id="btn-share" onClick={handleShare} style={{
          flex: '1', minWidth: 100,
          background: 'var(--surface-2)', color: 'var(--text)', border: '1px solid var(--border)',
          borderRadius: 'var(--radius-md)', padding: '12px 8px',
          fontFamily: 'inherit', fontSize: '0.875rem', fontWeight: 600, cursor: 'pointer',
        }}>
          📋 Copy
        </button>
        <button id="btn-print" onClick={handlePrint} style={{
          flex: '1', minWidth: 100,
          background: 'var(--surface-2)', color: 'var(--text)', border: '1px solid var(--border)',
          borderRadius: 'var(--radius-md)', padding: '12px 8px',
          fontFamily: 'inherit', fontSize: '0.875rem', fontWeight: 600, cursor: 'pointer',
        }}>
          🖨️ Print
        </button>
      </div>

      {toast && <div className="toast">{toast}</div>}
    </div>
  );
}
