package com.survivemum.app.data

import androidx.room.*
import kotlinx.coroutines.flow.Flow

/**
 * Data Access Object for AI-captured vital signs.
 * Connects computer vision outputs (rPPG, Pallor, Jaundice) to the UI.
 */
@Dao
interface VitalReadingDao {

    /**
     * Retrieves all AI readings for a patient in descending order.
     * Used to populate the 'Vital Trends' charts on the Patient Profile.
     */
    @Query("SELECT * FROM vital_readings WHERE patientId = :patientId ORDER BY timestamp DESC")
    fun getReadingsForPatient(patientId: String): Flow<List<VitalReadingEntity>>

    /**
     * Fetches the single most recent AI observation.
     * Critical for the 'Silent Guardian' status bar to show the current 
     * Heart Rate or Respiratory status.
     */
    @Query("SELECT * FROM vital_readings WHERE patientId = :patientId ORDER BY timestamp DESC LIMIT 1")
    suspend fun getLatestReading(patientId: String): VitalReadingEntity?

    /**
     * Inserts a new reading generated by the camera/microphone AI layers.
     * Uses REPLACE to update any reading with a matching ID.
     */
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertReading(reading: VitalReadingEntity)
}
